version: "3"

services:

  node:
    build: ./build
    container_name: node-api
    working_dir: /usr/src/app
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_PORT=81
      - TERM=xterm
    volumes:
      - ./app:/usr/src/app
    ports:
      - "81:3000"
    networks:
      - node_api_network
    command: "npm start"

networks:
  node_api_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/24
          gateway: 172.80.0.1